name: Build iOS App

on:
  push:
    branches:
      - master  # Eğer başka bir branch kullanıyorsanız burayı değiştirin.

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  # GitHub Secrets'ta eklediğiniz Expo Access Token
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Verify Expo Authentication
        run: eas whoami  # Bu komut token sayesinde girişin doğru olduğunu doğrular.

      - name: Build the iOS app
        run: eas build -p ios --profile development --non-interactive --skip-credentials-check
