name: Build iOS App

on:
  push:
    branches:
      - master  # Ana branch'iniz.

jobs:
  build-ios:
    runs-on: macos-latest  # Xcode için macOS ortamı gerekli.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # GitHub reposunu alır.

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'  # Kullandığınız Node.js sürümü.

      - name: Install dependencies
        run: |
          npm install  # Projenin bağımlılıklarını kurar.

      - name: Install Expo CLI
        run: |
          npm install -g expo-cli  # Expo CLI'yi kurar.

      - name: Install EAS CLI
        run: |
          npm install -g eas-cli  # EAS CLI'yi kurar.

      - name: Log in to Expo
        run: |
          echo ${{ secrets.EXPO_TOKEN }} | eas login --token  # Expo'ya giriş yapar.

      - name: Build the iOS app
        run: |
          eas build -p ios  # iOS uygulaması için build işlemini başlatır.
