name: Build iOS App

on:
  push:
    branches:
      - master  # Ana branşınızı kullanıyorsanız 'main', başka bir branş kullanıyorsanız onun adı.

jobs:
  build-ios:
    runs-on: macos-latest  # GitHub Actions yalnızca macOS üzerinde çalışacak şekilde yapılandırılmıştır.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Kodunuzu GitHub'dan alır.

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'  # Node.js sürümünüzü burada 22.12.0 olarak belirtiyoruz.
      
      - name: Install dependencies
        run: |
          npm install  # Proje bağımlılıklarını kurar.

      - name: Install Expo CLI
        run: |
          npm install -g expo-cli  # Expo CLI'yi global olarak kurar.

      - name: Build the iOS app
        run: |
          eas build -p ios  # iOS uygulaması için build işlemi başlatılır.
