name: Build iOS App with Xcode

on:
  push:
    branches:
      - master  # Eğer "master" branch kullanıyorsanız, yoksa kullandığınız branch ismini yazın.

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Create exportOptions.plist
        run: |
          cat <<EOF > exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string>${{ secrets.TEAM_ID }}</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

      - name: Build archive with xcodebuild
        run: |
          xcodebuild -workspace ios/KosuUygulama.xcworkspace \
                     -scheme KosuUygulama \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     archive -archivePath $PWD/build/KosuUygulama.xcarchive

      - name: Export IPA from archive
        run: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/KosuUygulama.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $PWD/build

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4

        with:
          name: KosuUygulama-IPA
          path: $PWD/build/KosuUygulama.ipa
