name: iOS Build (No Signing)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Ruby for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'

      - name: Install dependencies
        run: |
          gem install fastlane -NV
          bundle install

      - name: Build the app using Fastlane
        run: |
          cd ios
          fastlane gym --scheme YourAppScheme

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.ipa
          path: ios/build/*.ipa
