name: iOS Build (No Signing)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.12.0' # React Native sürümünüzle uyumlu bir sürüm seçin
        
    - name: Install dependencies
      run: |
        npm install
        if [ -d "ios" ]; then
          cd ios
          pod install
        else
          echo "No ios directory found!"
        fi

    - name: Build iOS app
    run: |
        cd ios
        xcodebuild -workspace KosuUygulama.xcworkspace -scheme KosuUygulama -configuration Release -sdk iphoneos clean archive -archivePath ${{ github.workspace }}/KosuUygulama.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    
    - name: Export IPA
      run: |
        xcodebuild -exportArchive -archivePath ${{ github.workspace }}/KosuUygulama.xcarchive -exportOptionsPlist ios/KosuUygulamaExportOptions.plist -exportPath ${{ github.workspace }}/KosuUygulama.ipa

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v4
      with:
        name: KosuUygulama.ipa
        path: ${{ github.workspace }}/KosuUygulama.ipa
