name: Build iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest  # Bu, GitHub'ın sağladığı macOS ortamını kullanacak
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Kullanmakta olduğunuz Node.js sürümünü belirleyin

    - name: Install dependencies
      run: npm install

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Build iOS app
      run: expo build:ios --no-wait
      env:
        EXPO_APPLE_ID: ${{ secrets.EXPO_APPLE_ID }}
        EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}

    - name: Upload .ipa to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ipa
        path: build/*.ipa
