name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.12.0' # React Native sürümünüzle uyumlu bir sürüm seçin

    - name: Install dependencies
      run: |
        npm install
        cd ios
        pod install

    - name: Build iOS app
      run: |
        cd ios
        xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -configuration Release -sdk iphoneos clean archive -archivePath ${{ github.workspace }}/YourApp.xcarchive

    - name: Export IPA
      run: |
        xcodebuild -exportArchive -archivePath ${{ github.workspace }}/YourApp.xcarchive -exportOptionsPlist ios/YourAppExportOptions.plist -exportPath ${{ github.workspace }}/YourApp.ipa

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v2
      with:
        name: YourApp.ipa
        path: ${{ github.workspace }}/YourApp.ipa
